dist: trusty
sudo: required
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install "g++-5"
  - sudo apt-get install cmake3
  - sudo apt-get install zlib1g-dev
  - sudo apt-get install libpng12-dev
  - sudo apt-get install libopenexr-dev 
  - sudo apt-get install cmake
  
language: cpp

compiler:
  - g++
  
branches:
  only:
  - develop

install:
  - pushd /tmp/
  - wget http://igg.unistra.fr/people/thery/itk.tgz
  - cd /usr/
  - sudo tar xf /tmp/itk.tgz
  - popd

script:
  - mkdir build
  - cd build
  - export CC=gcc-5
  - export CXX=g++-5
  - cmake .. && make
