#ifndef TEXTONIO_H
#define TEXTONIO_H

#include <ASTex/easy_io.h>
#include <ASTex/special_io.h>

#include <iostream>
#include <ASTex/easy_io.h>
#include <ASTex/special_io.h>
#include <cstdlib>

//Import a texton from a file generated by the original mathlab implem
namespace ASTex {


int import_texton(ASTex::ImageRGBd& texton, std::string file_path, ImageRGBd::PixelType &mean);
int import_texton(ASTex::ImageRGBd& texton, std::string file_path);

int export_texton(ASTex::ImageRGBd& texton, std::string file_path,
                  int order,
                  ImageRGBd::PixelType &mean);

}
#endif // TEXTONIO_H
