name: 'Continuous Integration ASTex'
on:
  pull_request:
     branches:
       - develop

jobs:

#  build-linux:
#    name: 'On Linux'
#    runs-on: ubuntu-24.04
#    steps:
#      - uses: actions/checkout@v1
#      - name: 'Package installations'
#        shell: bash
#        run: |
#          lsb_release -a
#          sudo apt update
#          sudo apt install libeigen3-dev libglfw3-dev libpng-dev libopenmpi-dev libopenexr-dev libimath-dev libinsighttoolkit5-dev libcgal-dev libsuitesparse-dev
#      - name: 'Trying to compile ASTex on Linux' 
#        run:  |
#          mkdir Build
#          cd Build
#          cmake ..
#          cmake --build . 

  build-windows:
    name: 'On Windows'
    runs-on: windows-2022
    # env: 
    #   VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
    steps:
      # - name: Export GitHub Actions cache environment variables
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
      #        core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - uses: actions/checkout@v1
      - name: 'install deps'
        run: vcpkg install zlib:x64-windows-release libpng:x64-windows-release eigen3:x64-windows-release
                        glfw3:x64-windows-release imath:x64-windows-release openexr:x64-windows-release 
                        itk:x64-windows-release cgal:x64-windows-release suitesparse:x64-windows-release 
                        glew:x64-windows-release tbb:x64-windows-release 
      - name: 'Trying to compile ASTex on Windows'
        run: |
          mkdir Build
          cd Build
          cmake .. "-DCMAKE_TOOLCHAIN_FILE=$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Release"
          cmake --build .

#  build-OsX:
#    name: 'On Mac'
#    runs-on: macos-13
#    steps:
#      - uses: actions/checkout@v1
#      - name: 'install deps'
#        run: brew install eigen glfw imath openexr openmpi itk cgal suitesparse tbb
#      - name: 'Trying to compile ASTEx on mac'
#        run:  |
#          mkdir Build
#          cd Build
#          cmake .. 
#          cmake --build . # This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
