name: 'Continuous Integration ASTex'
on:
  pull_request:
     branches:
       - develop

jobs:

  build-linux:
    name: 'On Linux'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: 'Trying to compile ASTex on Linux' 
        run:  |
          mkdir Build
          cd Build
          cmake ..
          cmake --build . 

  build-windows:
    name: 'On Windows'
    runs-on: windows-latest
    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
             core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: 'install deps'
        env: 
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
        run: |
          choco install gh
          vcpkg install zlib libpng eigen3 glfw3 imath openexr itk cgal suitesparse glew tbb 
      - uses: actions/checkout@v1
      - name: 'Trying to compile ASTex on Windows'
        run: |
          mkdir Build
          cd Build
          cmake --debug-find .. "-DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake"
          cmake --build .
  build-OsX:
    name: 'On Mac'
    runs-on: MyPortMac
    steps:
      - uses: actions/checkout@v1
      - name: 'Trying to compile ASTEx on mac'
        run:  |
          mkdir Build
          cd Build
          cmake --build . 
