name: 'Continuous Integration ASTex'
on:
  pull_request:
     branches:
       - develop

jobs:

#  build-linux:
#    name: 'On Linux'
#    runs-on: ubuntu-24.04
#    steps:
#      - uses: actions/checkout@v1
#      - name: 'Package installations'
#        shell: bash
#        run: |
#          lsb_release -a
#          sudo apt update
#          sudo apt install libeigen3-dev libglfw3-dev libpng-dev libopenmpi-dev libopenexr-dev libimath-dev libinsighttoolkit5-dev libcgal-dev libsuitesparse-dev
#      - name: 'Trying to compile ASTex on Linux' 
#        run:  |
#          mkdir Build
#          cd Build
#          cmake ..
#          cmake --build . 

  build-windows:
    name: 'On Windows'
    runs-on: windows-2022
    steps:
        - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
             core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: 'install deps'
        env: 
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
        run:
          vcpkg install zlib libpng eigen3 glfw3 imath openexr itk cgal suitesparse glew tbb 
      - uses: actions/checkout@v1
      - name: 'Trying to compile ASTex on Windows'
        run: |
          mkdir Build
          cd Build
          cmake .. "-DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake"
          cmake --build .

  build-OsX:
    name: 'On Mac'
    runs-on: macos-13
    steps:
      - name: install deps
        run:
          brew install eigen glfw imath openexr openmpi itk cgal suitesparse tbb
      - uses: actions/checkout@v1
      - name: 'Trying to compile ASTEx on mac'
        run:  |
          sudo xcode-select --switch /Library/Developer/CommandLineTools
          mkdir Build
          cd Build
          cmake .. 
          cmake --build . 
